---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.14.2  # put latest release tag from https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
